name: Build and push container

on: [ push ]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Build and push

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile
          tags: guestfs-ci:latest
